//version=1
// © carlosgatt1

strategy("Strategy-MAcross", shorttitle="Strategy-MAcross", overlay=true, initial_capital=10000)

// Revision:        2
// Author:          @carlosgatti 


// === INPUT MA LENGTHS ===
SMA_Fast=input(10, minval=1)
SMA_Slow=input(20, minval=1)
s1 = sma(close, SMA_Fast)
s2 = sma(close, SMA_Slow)


// === INPUT BACKTEST RANGE ===
fromMonth = input(defval = 1,    title = "From Month",  minval = 1, maxval = 12)
fromDay   = input(defval = 1,    title = "From Day",    minval = 1, maxval = 31)
fromYear  = input(defval = 2021, title = "From Year",   minval = 1970)
thruMonth = input(defval = 1,    title = "Thru Month",  minval = 1, maxval = 12)
thruDay   = input(defval = 1,    title = "Thru Day",    minval = 1, maxval = 31)
thruYear  = input(defval = 2112, title = "Thru Year",   minval = 1970)


// === INPUT SHOW PLOT ===
showDate  = input(defval = true, title = "Show Date Range")


// === FUNCTION EXAMPLE ===
start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)        // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)        // backtest finish window
window()  => time >= start and time <= finish ? true : false       // create function "within window of time"

// === LOGIC ===
buy = crossover(s1, s2)
sell = crossunder(s1, s2)
ordersize = floor(strategy.equity/close)


// === EXECUTION ===
strategy.entry("long", strategy.long, ordersize, when=buy)
strategy.close("long", when=sell)


// === PLOTTING ===
bgcolor(color = showDate and window() ? gray : na, transp = 90) 
plot(s1, color=yellow, linewidth=2)
plot(s2, color=red, linewidth=2)